services:
  backend_service:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .venv
            - .idea
            - .git
        - action: rebuild
          path: requirements.txt
    command: /start-django
    env_file:
      - path: .env
        required: true
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - postgres_service
      - minio_service
      - redis_service
      - rabbit_service

  redis_service:
    image: redis/redis-stack:latest
    env_file: .env
    ports:
      - '6380:6379'

  rabbit_service:
    image: rabbitmq:3-management
    env_file: .env
    ports:
      - '15672:15672'
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}

  minio_service:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    env_file: .env
    command: server /data --console-address :9001
    volumes:
      - minio_volume:/data

  celery:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file:
      - .env
    command:
      - /start-celeryworker
    depends_on:
      - postgres_service
      - minio_service
      - redis_service
      - rabbit_service

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env
    command:
      - /start-celerybeat
    depends_on:
      - postgres_service
      - minio_service
      - redis_service
      - rabbit_service

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - pg_data_p19:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  flower:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env
    command:
      - /start-flower


  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend_service
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  pg_data_p19:
  media_volume:
  static_volume:
  minio_volume: